### ISSUE TITLE
Exception im Debug Modus

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-list-bundle#1]
**Context**
Contao version: 4.9.7
Bundle version: 1.25.0
PHP version: 7.4

**Description**

Ich habe den Debugmodus angeschaltet und bekomme beim ausführen der Auflistung im FE folgende Meldung

`Uncaught PHP Exception TypeError: "Argument 2 passed to HeimrichHannot\ListBundle\Lists\DefaultList::isDcMultilingualActive() must be of the type array, null given, called in /*/vendor/heimrichhannot/contao-list-bundle/src/Lists/DefaultList.php on line 210" at /*/vendor/heimrichhannot/contao-list-bundle/src/Lists/DefaultList.php line 378 
`
Ohne Debugmodus funktioniert es allerdings. Den brauche ich aber damit das twig-Zeug nicht cached wird.

**Comment by Defcon0** [comment]
Mhm, den Fehler bekommst du, weil in Zeile Z. 179 in `DefaultList` auch nach dem Aufruf von `loadDc()` kein DCA zurückgeliefert wird. Das dürfte eigentlich nicht passieren. Was befindet sich in `$filter->dataContainer` in Zeile 178 bevor der Fehler geworfen wird?

**Comment by Defcon0** [comment]
Gibt es hier was neues?
